name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v1.0.0
        with:
          github_user_name: YourGitHubUsername
          output_dir: dist/
          filename: snake.svg

      - name: Commit and push the generated snake.svg
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@users.noreply.github.com"
          message: "Add snake animation"
          add: "dist/snake.svg"
