name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and generate Snake Animation
        run: |
          npm install -g github-readme-stats
          node -e "
            const ghStats = require('github-readme-stats');
            ghStats({
              username: 'YourGitHubUsername', 
              output: './dist/snake.svg'
            }).then(() => console.log('Snake generated!'));
          "

      - name: Commit and push the generated snake.svg
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@users.noreply.github.com"
          message: "Add snake animation"
          add: "dist/snake.svg"
